version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=EyeQlytics
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eye_qlytics
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=VASU9999007.
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - springdoc.api-docs.enabled=true
      - springdoc.swagger-ui.enabled=true
      - spring.web.cors.allowed-origins=*
      - spring.web.cors.allowed-methods=*


    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: VASU9999007.
      MYSQL_DATABASE: eye_qlytics
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
